sonar.projectKey=Notes-App
sonar.projectName=Notes App
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test,frontend/src
sonar.test.inclusions=backend/test/**/*.spec.js,frontend/src/**/*.test.js,frontend/src/**/*.test.jsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
